export type AgentStatus = "running" | "stopped" | "unknown";

export type RuntimeStatus = "starting" | "idle" | "busy" | "tool_running" | "response_missing" | "shutting_down" | "stopped";

export type HealthStatus = "healthy" | "degraded" | "unhealthy";

export type OrphanClearReason = "swarm_send_message" | "swarm_assign_task" | "swarm_stop_agent" | "preflight_message";

export type SwarmAgent = {
	id: string;
	role: string;
	roleKind: string;
	roleKindExplicit?: boolean;
	capabilities: string[];
	activeTaskIds: string[];
	maxConcurrentTasks: number;
	status: AgentStatus;
	runtimeStatus: RuntimeStatus;
	health: HealthStatus;
	lastHeartbeatAt?: string;
	lastSessionStartAt?: string;
	lastAgentStartAt?: string;
	lastAgentSettledAt?: string;
	lastSettleNotifyAt?: string; // persisted cooldown for agent_settled->root idle/open-work notify
	lastAckDebtNotifyAt?: string; // R25: persisted cooldown for agent_settled/stopAgent→root ack-debt notify
	// === Issue 86: priority-high interrupt-on-delivery (recipient-side rate-limit ledger) ===
	// Last timestamp a `ctx.abort()` was invoked by the recipient's input hook in response to a
	// priority:"high" swarm message. Persisted on the recipient agent record; root pseudo-
	// agent is exempt. A second high-priority inject within PI_SWARM_HIGH_INTERRUPT_WINDOW_MS
	// (default 30000) does NOT re-abort (suppressed via `message.interrupt_suppressed` trace).
	// Cleared on respawn via ensureAgentDefaults (existing pattern); no extra logic needed.
	lastHighInterruptAt?: string;
	// === Issue 25 Phase 2: worker dry-run reconcile rate-limit ledger (proposal §K.1) ===
	// Last worker dry-run reconcile timestamp. Persisted so a worker that calls swarm_reconcile
	// more often than PI_SWARM_RECONCILE_DRYRUN_WORKER_RATE_MS gets RECONCILE_RATE_LIMITED without
	// a separate ledger. Root/admin is exempt; the gate is enforced at the tool boundary.
	lastReconcileDryRunAt?: string;
	lastToolAt?: string;
	lastShutdownAt?: string;
	pid?: number;
	// Park/drain flag: a paused agent is skipped by the reuse pool (findReusableAgent) but is NOT killed
	// and still appears in status/list. Cleared by resume (delete) so absent == not paused.
	paused?: boolean;
	// === Issue 82: explicit reuse lease + park mechanism (P0, R9 a3 graveyard) ===
	// When the root wants a worker to outlive its task scope, it stamps a lease on the
	// agent record. The task-close sweep honors the lease: `reuse` skips the sweep entirely
	// (worker is kept alive for cross-task reuse); `park` pauses (`paused=true`) instead of
	// stopping (worker pane is preserved for inspection / revival). Both leases auto-expire at
	// `leaseUntil`; the default behavior (retire on task close) applies once expired. Additive;
	// absent fields == default behavior. Cleared by `/swarm agent lease <id> --clear` or by
	// any explicit lease-removal call (e.g. assignment-tool resets).
	leaseKind?: "reuse" | "park";
	leaseUntil?: string;
	leaseReason?: string;
	// === Issue 82 (review item 1): heartbeat-GC probe-throttle ledger ===
	// ISO timestamp of the most recent tmux probe fired by `agentHeartbeatGCLocked` gate 2.
	// Pre-policy agents simply lack the field (== never probed). The GC skips a gate-2 probe
	// unless `lastProbeAt` is older than `probeAfterMs` (2× PI_SWARM_AGENT_HEARTBEAT_STALE_MS),
	// so the per-tick probe rate is bounded at roughly one probe per agent per 20 minutes by
	// default — even for a graveyard-shape swarm where lastHeartbeatAt is stale forever.
	// Absent on legacy agents; treated as "never probed" by the gate.
	lastProbeAt?: string;
	tmuxSession: string;
	tmuxWindow: string;
	tmuxTarget: string;
	model: string;
	provider: string;
	cwd: string;
	mailbox: string;
	// Issue 26 — task-close worker sweep (auto-stop task-scoped workers). Additive durable link
	// from an agent to the task it was FRESHLY SPAWNED FOR. Stamped at spawn-for-task time in
	// `tools/tasks.ts:swarm_assign_task` (autoSpawn/spawnIsolated path) when the agent is a new
	// record for that task; never overwritten by unrelated task ids. Read by the task-close sweep
	// in `taskgraph.ts:sweepTaskWorkersLocked` to decide whether an otherwise-idle worker should be
	// swept when its task closes. Absent on reuse-pool agents that were not spawned for the task
	// — they are swept ONLY when their only active task is the closing one.
	spawnedForTaskId?: string;
	// Identity provenance (additive, optional). Stamped whenever the EFFECTIVE identity file is
	// (re)generated by writeEffectiveIdentity (spawn / swarm_agent_identity refresh / swarm_reload_identity).
	identityVersion?: number; // monotonically bumps when the effective content (base+override) changes
	identityHash?: string; // sha256 hex of the effective content (base + override body)
	identityLoadedAt?: string; // ISO timestamp of the last effective-identity write
	createdAt: string;
	updatedAt: string;
};

// In-flight orphan-spawn watchdog entry (Issue 14). Pushed when swarm_spawn_agent mints a NEW agent
// record (not restart/register/pool-reuse) and removed when the engine either (a) detects a follow-up
// delivery within the ORPHAN_SPAWN_WARNING_TIMEOUT_MS window or (b) the timer fires and emits
// `agent.spawn.orphan_warning` (or `orphan_resolved_late`). Persisted on SwarmState so process
// restart can audit stranded entries; the in-process timer handle lives on a module-level Map
// (NOT on this record) because NodeJS.Timeout is not JSON-serializable.
export type RecentSpawn = {
	agentId: string;
	spawnedAt: string; // ISO; mirrors agent.createdAt for the just-created record
	deadlineAt: string; // ISO; spawnedAt + ORPHAN_SPAWN_WARNING_TIMEOUT_MS
	// Issue 16: identity of the spawning root session, stamped unconditionally at
	// armOrphanWatch time. The pre-clear predicate in swarm_assign_task compares these against
	// process.pid + process.env.PI_SWARM_SESSION_STARTED_AT at compare time. Both fields are
	// optional only for backward-compat reads of legacy state (no production code path leaves
	// them undefined for entries armed after this change).
	spawnedByPid?: number;
	spawnedBySessionStartedAt?: string;
};

// Internal reusable-agent lookup used by task tooling (not a public worker tool).
// Recommends the idle, healthy, tmux-alive agent with the fewest active tasks.
// `matchKind` is the rationale for inclusion (roadmap issue 10, reuse-misroute fix):
//   "exact" = role-kind check + capabilities intersect cleanly
//   "substring-collapsed" = re-derived roleKind matches but agent id contains a different role keyword
//                           (caller may want to log/skip these)
//   "fallback" = no role-kind match; matched via capabilities or agentId escape-hatch
export type ReusableAgentMatch = {
	agentId: string;
	roleKind: string;
	runtimeStatus: string;
	health: HealthStatus;
	tmuxAlive: boolean;
	activeTaskIds: string[];
	capabilities: string[];
	matchKind?: "exact" | "substring-collapsed" | "fallback";
};
