// === swarm/identity.ts — auto-extracted from index.ts (verbatim bodies) ===
import { mkdir, readFile, writeFile, appendFile, rm, stat, rename, readdir, realpath } from "node:fs/promises";
import { existsSync, readFileSync } from "node:fs";
import { join, dirname, relative, sep } from "node:path";
import { createHash, randomUUID } from "node:crypto";
import type { Paths, SwarmAgent, SwarmState } from "./types.ts";
import { MEMORY_POLICY_DOC } from "./constants.ts";
import { currentAgentId, currentModel, currentProvider } from "./session.ts";
import { identityPath, mailboxPath, paths, trace } from "./state.ts";
import { now, safeId } from "./utils.ts";
import { tmux } from "./tmux.ts";

// Centralized authority check used by every server-side mutation that depends on identity. Phase 1
// deliberately keeps this strict (orchestrator-only); expanded admin roles live in a later roadmap
// issue. Any tool that allows `force`/cancellation must consult this helper instead of trusting
// caller-supplied parameters.
export function isOrchestratorAuthority(agentId: string = currentAgentId()): boolean {
	return agentId === "orchestrator";
}

// The orchestrator is a human-driven coordinating session with no dedicated swarm tmux pane.
// Ensure it always has a routable pseudo-agent record + mailbox so swarm_send_message(to=orchestrator)
// works from any peer, and so delivery to it is treated as mailbox-only rather than a tmux failure.
export function ensureOrchestrator(st: SwarmState, cwd: string, p: Paths): SwarmAgent {
	const ts = now();
	const existing = st.agents["orchestrator"];
	if (existing) {
		// Self-heal the mailbox-only contract on every refresh. The orchestrator is a pseudo-agent with
		// NO dedicated swarm pane, so delivery must always be mailbox-only. An older code version (or a
		// manually-edited state) could have left the orchestrator attached to a real tmux pane target,
		// which makes peer messages get tmux-injected into that pane instead of delivered to the mailbox.
		// Re-normalize the structural fields so any such "misled" record is corrected on the next
		// session_start/ensure. A custom role/role-text is preserved.
		existing.roleKind = "orchestrator";
		existing.tmuxTarget = "unknown";
		existing.tmuxSession = st.tmuxSession;
		existing.tmuxWindow = "orchestrator";
		existing.mailbox = relative(cwd, mailboxPath(p, "orchestrator"));
		existing.maxConcurrentTasks = 99;
		existing.lastHeartbeatAt = ts;
		existing.lastSessionStartAt = ts;
		existing.updatedAt = ts;
		existing.status = "running";
		if (existing.health === "unhealthy") existing.health = "healthy";
		return existing;
	}
	const agent: SwarmAgent = {
		id: "orchestrator",
		role: "Swarm orchestrator (human-driven coordinating session). Receives messages via mailbox; no dedicated swarm tmux pane, so delivery is mailbox-only.",
		roleKind: "orchestrator",
		capabilities: [],
		activeTaskIds: [],
		maxConcurrentTasks: 99,
		status: "running",
		runtimeStatus: "idle",
		health: "healthy",
		lastHeartbeatAt: ts,
		lastSessionStartAt: ts,
		tmuxSession: st.tmuxSession,
		tmuxWindow: "orchestrator",
		tmuxTarget: "unknown",
		model: currentModel(),
		provider: currentProvider(),
		cwd,
		mailbox: relative(cwd, mailboxPath(p, "orchestrator")),
		createdAt: ts,
		updatedAt: ts,
	};
	st.agents["orchestrator"] = agent;
	st.delivered["orchestrator"] ||= [];
	return agent;
}

// NOTE: the `MEMORY_POLICY_DOC` constant ("docs/swarm-memory.md") is declared in the memory-surface
// region (see ~line 1450, owned by implement_memory_policy). This identity region REFERENCES it
// read-only when appending the `## Memory protocol` link to generated agent identity, so there is no
// redeclaration here. Both regions stay disjoint; the constant value is shared and identical.

export function buildIdentityMarkdown(state: SwarmState, agent: SwarmAgent) {
	return `# Swarm Agent Identity: ${agent.id}\n\n` +
		`> This file is generated by the pi swarm extension. It is the durable role/identity card for this agent.\n\n` +
		`## Identity\n\n` +
		`- Agent ID: \`${agent.id}\`\n` +
		`- Role: ${agent.role}\n` +
		`- Swarm ID: \`${state.swarmId}\`\n` +
		`- Model: \`${agent.provider}/${agent.model}\`\n` +
		`- CWD: \`${agent.cwd}\`\n` +
		`- Tmux target: \`${agent.tmuxTarget}\`\n` +
		`- Mailbox: \`${agent.mailbox}\`\n\n` +
		`## Operating Protocol\n\n` +
		`1. Treat this identity file as your role-specific AGENT.md.\n` +
		`2. Coordinate with peers using \`swarm_send_message\`; do not ask the human to relay swarm traffic.\n` +
		`3. Check your mailbox with \`swarm_check_mailbox\` when idle or after receiving swarm traffic. Here, idle means you have no active tool calls or immediate task steps; if you are waiting more than ~10 seconds, poll pending mailbox messages.\n` +
		`4. Use \`swarm_list_agents\` before messaging a peer whose existence you have not verified.\n` +
		`5. Use \`swarm_trace\` and \`swarm_capture_agent_pane\` when debugging coordination issues.\n` +
		`6. Stay within your role unless the orchestrator explicitly changes your assignment.\n\n` +
		`## ACK Protocol\n\n` +
		`- For every swarm message with \`requiresAck=true\`, you MUST acknowledge it with \`swarm_ack_message\`.\n` +
		`- As soon as you start work, call \`swarm_ack_message\` with the message id and \`status=seen\` or \`status=processing\`.\n` +
		`- When finished, send a result back to the requester with \`swarm_send_message(replyTo=<original-message-id>)\` or \`swarm_task_message\`, then call \`swarm_ack_message(status=done, resultMessageId=<result-message-id>)\`. ACK is lifecycle only; it is not the work result.\n` +
		`- Never leave a requiresAck message unacked. Reconcile surfaces unacked delivered messages as \`ack_missing\`.\n\n` +
		`## Lifecycle\n\n` +
		`- Start by reading this identity when role details are unclear.\n` +
		`- If an initial task is present, begin it after reading identity; do not wait indefinitely for another instruction.\n` +
		`- If no task is present, poll your mailbox periodically and remain available until the orchestrator stops or reassigns you.\n` +
		`- Report completion, blockers, and role conflicts to the coordinating agent named in your task or to the orchestrator.\n\n` +
		`## Peer Discovery\n\n` +
		`- Use \`swarm_list_agents\` to verify peer IDs and tmux targets.\n` +
		`- Use \`swarm_agent_identity\` to inspect your own or a peer's durable role card.\n` +
		`- If a target peer does not exist, report the missing peer instead of repeatedly sending messages.\n\n` +
		`## Review Expectations\n\n` +
		`- Be explicit about findings, risks, assumptions, and evidence paths.\n` +
		`- Prefer small, verifiable messages over large unstructured dumps.\n` +
		`- If a requested action conflicts with this identity, explain the conflict and ask for reassignment.\n\n` +
		`## Memory protocol\n\n` +
		`Read and follow \`${MEMORY_POLICY_DOC}\`. Read memory at task start and when blocked; propose only after a passing/approved run with file-backed evidence; never promote pane-only/ack-only claims.\n`;
}

export function identityPrompt(cwd: string, identityRelPath: string) {
	return `\n\n[PI-SWARM IDENTITY]\nYour durable swarm identity is stored at ${identityRelPath}. Read it before acting when you need role details. Treat it as your agent-specific AGENT.md.\nFor any swarm message with requiresAck=true, you MUST acknowledge it with swarm_ack_message. If requiresResponse=true, send a result message first and ack done with resultMessageId.\n[/PI-SWARM IDENTITY]`;
}

// Override file path: `.pi/swarm/agents/<id>.override.md`. This file is USER-EDITABLE and is ONLY EVER
// READ by generation — it is never written or deleted by the extension, so edits survive regeneration.
export function overridePath(p: Paths, agentId: string) {
	return join(p.agentsDir, `${safeId(agentId)}.override.md`);
}

export function identityHashOf(text: string) {
	return createHash("sha256").update(text, "utf8").digest("hex");
}

// Rebuild + persist the EFFECTIVE identity for an agent: generated base (buildIdentityMarkdown, which
// includes the Memory protocol link) + optional override-append + an Identity provenance footer. The
// effective markdown is written to `<id>.md`; the override file (`<id>.override.md`) is read-only.
//
// MUST be called under the swarm lock: it mutates `agent.identityVersion/identityHash/identityLoadedAt`
// and the caller writes state afterward. version bumps when the effective CONTENT (base + override
// body, excluding the provenance footer) changes since the last stamp, or on first creation — so a
// no-op rewrite is idempotent, while an override add/remove/role-change bumps the version.
export async function writeEffectiveIdentity(cwd: string, p: Paths, state: SwarmState, agent: SwarmAgent, opts?: { reason?: string }) {
	const base = buildIdentityMarkdown(state, agent);
	let overrideText = "";
	let overridePresent = false;
	const ovPath = overridePath(p, agent.id);
	if (existsSync(ovPath)) {
		const raw = (await readFile(ovPath, "utf8")).trim();
		if (raw) {
			overridePresent = true;
			overrideText = raw;
		}
	}
	// Effective content (base + override). The provenance footer is computed from this hash but is NOT
	// part of the hashed content, keeping version-bump detection stable across provenance-only rewrites.
	const content = overridePresent
		? `${base}\n<!-- PI-SWARM IDENTITY OVERRIDE START -->\n## Custom instructions (from override)\n\n${overrideText}\n\n<!-- PI-SWARM IDENTITY OVERRIDE END -->\n`
		: base;
	const contentHash = identityHashOf(content);
	const ts = now();
	const changed = !agent.identityHash || agent.identityHash !== contentHash;
	const version = changed ? (agent.identityVersion ?? 0) + 1 : (agent.identityVersion ?? 0);
	const shortHash = contentHash.slice(0, 12);
	const markdown = `${content}\n## Identity provenance\n\n` +
		`- Version: \`${version}\`\n` +
		`- Hash: \`${shortHash}\` (sha256 of base + override)\n` +
		`- Loaded at: \`${ts}\`\n` +
		`- Override present: \`${overridePresent}\`${overridePresent ? ` (\`${relative(cwd, ovPath)}\`)` : ""}\n`;
	// Stamp the agent record so callers (which already write state) persist provenance.
	agent.identityVersion = version;
	agent.identityHash = contentHash;
	agent.identityLoadedAt = ts;
	agent.updatedAt = ts;
	await writeFile(identityPath(p, agent.id), markdown, "utf8");
	await trace(p, "agent.identity.write", { agentId: agent.id, version, hash: shortHash, overridePresent, reason: opts?.reason || "effective", file: relative(cwd, identityPath(p, agent.id)) });
	return { markdown, version, hash: contentHash, shortHash, overridePresent, changed, loadedAt: ts };
}
